"""
sphinx configuration for the qis documentation

Two things are generated at build time rather than checked in:

1. ``api/index.rst`` is written from the symbols exported by ``qis/__init__.py``. The public API
   is defined as the export list, so the reference follows the exports rather than the module
   tree, and moving a module between subpackages costs no documentation change.
2. ``_included/`` mirrors ``qis/docs/``. Those notes ship inside the package and are referenced
   from docstrings by their package path, so they stay where they are and are copied in here
   with their images, keeping one source of truth.
"""

# packages
import importlib.metadata
import inspect
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List

import matplotlib

matplotlib.use('Agg')  # the build host has no display; must precede any qis import

DOCS_DIR = Path(__file__).parent
REPO_ROOT = DOCS_DIR.parent
sys.path.insert(0, str(REPO_ROOT))

project = 'qis'
author = 'Artur Sepp'
copyright = '2026, Artur Sepp'
release = importlib.metadata.version('qis')
version = '.'.join(release.split('.')[:2])

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'myst_parser',
]

# the house convention is Google-style; factorlasso uses numpydoc and is documented separately
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_use_admonition_for_notes = True
# render an Attributes: block as :ivar: fields on the class rather than as separate attribute
# directives, which would otherwise duplicate the members autodoc already emits for a dataclass
napoleon_use_ivar = True

autosummary_generate = True
autodoc_typehints = 'description'  # signatures stay readable; types render in the body
autodoc_member_order = 'bysource'
autodoc_default_options = {'members': True, 'undoc-members': True, 'show-inheritance': True}

myst_enable_extensions = ['colon_fence', 'deflist']  # linkify needs an extra dependency
myst_heading_anchors = 3

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/', None),
}

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
source_suffix = {'.rst': 'restructuredtext', '.md': 'markdown'}

html_theme = 'furo'
html_title = f"qis {release}"
html_static_path = []

# suppress the warning autosummary emits for symbols that are re-exported under a short name
suppress_warnings = ['autosummary']

API_HEADER = """..
   Generated by docs/conf.py from the qis export list. Do not edit by hand.

API reference
=============

Public means exported from ``qis/__init__.py``. Everything else is internal and may change.
This page is regenerated on every build, so it cannot drift from the exports.

"""

SECTION_ORDER = ['Enums', 'Dataclasses', 'Classes', 'Functions']


def _classify(name: str,
              obj: Any,
              ) -> str:
    """
    Bucket an exported symbol for the reference page.

    Args:
        name: exported name
        obj: the exported object

    Returns:
        one of ``SECTION_ORDER``
    """
    import dataclasses
    from enum import Enum
    if inspect.isclass(obj):
        if issubclass(obj, Enum):
            return 'Enums'
        if dataclasses.is_dataclass(obj):
            return 'Dataclasses'
        return 'Classes'
    return 'Functions'


def _write_api_index() -> None:
    """Write ``api/index.rst`` from the current qis export list."""
    import qis

    sections: Dict[str, List[str]] = {key: [] for key in SECTION_ORDER}
    for name in sorted(dir(qis)):
        if name.startswith('_'):
            continue
        obj = getattr(qis, name)
        if inspect.ismodule(obj):
            continue
        if not (inspect.isclass(obj) or inspect.isfunction(obj) or inspect.isbuiltin(obj)):
            continue
        sections[_classify(name=name, obj=obj)].append(name)

    lines = [API_HEADER]
    for section in SECTION_ORDER:
        names = sections[section]
        if len(names) == 0:
            continue
        # rst is whitespace-significant: the blank line after the option block is what makes
        # the entries content rather than options, and without it the toctree stays empty
        lines.append(f"{section}\n{'-' * len(section)}\n\n")
        lines.append(f"{len(names)} exported.\n\n")
        lines.append(".. autosummary::\n   :toctree: generated\n   :nosignatures:\n\n")
        lines.extend(f"   qis.{name}\n" for name in names)
        lines.append("\n")

    api_dir = DOCS_DIR.joinpath('api')
    api_dir.mkdir(exist_ok=True)
    api_dir.joinpath('index.rst').write_text(''.join(lines), encoding='utf-8')


def _mirror_package_notes() -> None:
    """Copy ``qis/docs/`` into ``docs/_included/`` so the toctree can reach it with its images."""
    source = REPO_ROOT.joinpath('qis', 'docs')
    target = DOCS_DIR.joinpath('_included')
    if target.exists():
        shutil.rmtree(target)
    if source.exists():
        shutil.copytree(source, target)


def setup(app: Any) -> None:
    """Generate the API index and mirror the package notes before the read phase."""
    _mirror_package_notes()
    _write_api_index()
